const type = {
  SET_USER_PROFILE: 'SET_USER_PROFILE',
  USER_LOADING: 'USER_LOADING',
  UPDATE_USER: 'UPDATE_USER',
  USER_SIGN_UP: 'USER_SIGN_UP',
  RESET_USER_PASSWORD: 'RESET_USER_PASSWORD',
  USER_LOGOUT: 'USER_LOGOUT'
}

export default type
