const type = {
  SET_TASKS: 'SET_TASKS',
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
  SET_DONE: 'SET_DONE',
  SET_IMPORTANT: 'SET_IMPORTANT',
  SET_PIN_TO_TOP: 'SET_PIN_TO_TOP',
  CHANGE_FILTER: 'CHANGE_FILTER',
  SEARCH: 'SEARCH'
}

export default type
